//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeregindenAsiriFazlaUltraSuperMukemmelProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayetler
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Sikayet { get; set; }
        public string Yorum { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
